name: Update Stock Data

on:
  schedule:
    - cron: '0 20 * * 1-5'  # Runs when the stock market closes
  workflow_dispatch:
    inputs:
      symbol:
        description: 'Stock symbol'
        required: true
        default: 'HITI'

jobs:
  update-stock-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch stock data
      run: |
        symbol=${{ github.event.inputs.symbol || 'HITI' }}
        curl "https://api.twelvedata.com/time_series?apikey=${{ secrets.TWELVEDATA_API_KEY }}&interval=1week&symbol=$symbol&exchange=NASDAQ&format=JSON&outputsize=52" -o assets/stock-data.json

    - name: Commit and push changes
      run: |
        git config --local user.email "brittonkfischer@gmail.com"
        git config --local user.name "nottirb"
        git add assets/stock-data.json
        git commit -m "Update stock data" || echo "No changes to commit"
        git push
